Define per-AZ instancegroups for worker nodes
ministryofjustice/cloud-platform-infrastructure pull request #902
Opened 2020-09-25 11:16 UTC by vijay-veeranki

This is related to [2272](https://github.com/ministryofjustice/cloud-platform/issues/2272)

This will help to alter our kops config to control which AZ our worker nodes are created.

Also updated the recycle node job script to handle multiple AZ ig.

2020-09-25 11:22 UTC, digitalronin requested changes
Is there any way we can label the worker node instance groups with an additional label like "WORKER_NODES" or something?

It would be nice if we could come up with something where we don't need to keep editing the `recycle-node.rb` script every time we rename an instance group (e.g when we upgrade kubernetes).

If we had a "static" label in addition to the node group name, we could tell the script to pick a node to recycle from all the instancegroups which have that tag.

2020-09-25 11:25 UTC, digitalronin requested changes

2020-09-25 11:25 UTC, digitalronin commented on recycle-node.rb
> +  worker_instance_group = docs.last(3)
Per my comment above, can we identify the worker node instance groups via a label?

If we can do that, then we don't need to worry about their position in the YAML file (i.e. `last(3)`). This is less brittle, so we won't break stuff if we reorder the sections of the yaml file.

2020-09-25 11:25 UTC, digitalronin commented on recycle-node.rb
>  def get_worker_instance_group_size
We need to rename this method if it counts workers from multiple node groups. How about `target_worker_node_count` ?

2020-09-28 11:17 UTC, vijay-veeranki commented
Hi @digitalronin,

Updated the changes as suggested, can you please look in to it?

2020-09-28 11:31 UTC, poornima-krishnasamy submitted a review, later dismissed

2020-09-28 14:16 UTC, poornima-krishnasamy approved these changes

2020-09-28 14:22 UTC, merged